### PR TITLE
Refactor ADPC

### LINKED ISSUE #280: Refactor ADPC following the new OCEAN Specs
The new ADPC specs will be applied in the OCEAN studies. We need to update the test ADPC for the new specs.

Adding the following variables in the ADPC.

1. Set AVALCAT1 (Analysis Value Category 1) = AVALC. [This variable impact the PKCT01 and 1/3 imputation rule.] 
2. Set NFRLT (Nom. Rel. Time from Analyte First Dose)  = NRELTM1 [This variable impact the PKCT01 and 1/3 imputation rule.] 
3. Set AFRLT (Act. Rel. Time from Analyte First Dose) = ARELTM1
4. Set NRRLT (Nominal Rel. Time from Ref. Dose) = NRELTM2
5. Set ARRLT (Actual Rel. Time from Ref. Dose) = ARELTM2
6. Add ANL02FL (Analysis Flag 02) == "Y" for all records. This variable needs to be applied in the data preprocessing step in all TLGs.

### PR DESCRIPTION
**Pull request by qiliu1013**
fixed #280

### CODE REVIEW

**Review by shajoezhu — CHANGES_REQUESTED** [review]
hi @qiliu1013 , there was a minor bug in the yml file, i just fixed. can you please

1. update and recompile the dataset
2. please update radab function accordingly as well. I am getting the following error message

```
> cadab_new <- radab(cadsl_new, cadpc_new, seed = 1, na_vars = list()) %>% `attr<-`("creation date", Sys.Date())
Error in `dplyr::select()`:
! Can't subset columns that don't exist.
✖ Column `ARELTM1` doesn't exist.
Backtrace:
  1. ... %>% `attr<-`("creation date", Sys.Date())
 14. dplyr:::select.data.frame(...)
```
Thanks

**Comment by qiliu1013** [comment]
> hi @qiliu1013 , there was a minor bug in the yml file, i just fixed. can you please
> 
> 1. update and recompile the dataset
> 2. please update radab function accordingly as well. I am getting the following error message
> 
> ```
> > cadab_new <- radab(cadsl_new, cadpc_new, seed = 1, na_vars = list()) %>% `attr<-`("creation date", Sys.Date())
> Error in `dplyr::select()`:
> ! Can't subset columns that don't exist.
> ✖ Column `ARELTM1` doesn't exist.
> Backtrace:
>   1. ... %>% `attr<-`("creation date", Sys.Date())
>  14. dplyr:::select.data.frame(...)
> ```
> 
> Thanks

@shajoezhu, I updated ADAB, however `apply_metadata(adpc, "metadata/ADPC.yml")` still doesn't work for me.

**Comment by shajoezhu** [comment]
Thanks @qiliu1013 , I have made a few updates. 

hey @edelarua, I was wondering if I could get second opinion as well? Thanks!

**Review by edelarua — APPROVED** [review]
Lgtm! @qiliu1013 @shajoezhu

**Review by shajoezhu — APPROVED** [review]

**Pull request merged**
