### PR TITLE
Fix distribution of IGA data in `adlb` after refactoring

### LINKED ISSUE #4: Update direction of abnormalities in ADLB
Right now in ADLB all parameters have abnormalities defined both high and low directions. To make this more realistic, I suggest that each parameter is assigned as follows:

ALT - Low
CRP - Both
IGA - High

The change should apply to ATOXGR / BTOXGR as well as ANRIND / BNRIND and related variables.

Provenance: 
```
Creator: anajens
```

### PR DESCRIPTION
**Pull request by edelarua**
Fixes missing direction in `ANRIND` for `IGA` data.

Closes #4

### CODE REVIEW

**Review by Melkiades — APPROVED** [review]
Lgtm! I checked now and it seems that the change affects the other mentioned variables. Still I wanted to ask you if it is not the other way round for the aval mean. In the issue ALT should be Low and IGA high, while at the moment it seems the other way round, am I wrong?

**Comment by Melkiades** [comment]
> Lgtm! I checked now and it seems that the change affects the other mentioned variables. Still I wanted to ask you if it is not the other way round for the aval mean. In the issue ALT should be Low and IGA high, while at the moment it seems the other way round, am I wrong?

Na forget about it. Everything should be fine with these parameters
 ```
dplyr::mutate(ANRLO = dplyr::case_when(
      PARAMCD == "ALT" ~ 7,
      PARAMCD == "CRP" ~ 8,
      PARAMCD == "IGA" ~ 0.8
    )) %>%
    dplyr::mutate(ANRHI = dplyr::case_when(
      PARAMCD == "ALT" ~ 55,
      PARAMCD == "CRP" ~ 10,
      PARAMCD == "IGA" ~ 3
    )) %>%
    dplyr::mutate(ANRIND = factor(dplyr::case_when(
      AVAL < ANRLO ~ "LOW",
      AVAL > ANRHI ~ "HIGH",
      TRUE ~ "NORMAL"
    ))) %>%
```

**Review by Melkiades — CHANGES_REQUESTED** [review]
mmh actually could be the other way round:
```r
a <- random.cdisc.data::cadlb
a %>% filter(PARAMCD == "ALT") %>% pull(ANRIND) %>% table()
```

**Comment by edelarua** [comment]
> mmh actually could be the other way round:
> 
> ```r
> a <- random.cdisc.data::cadlb
> a %>% filter(PARAMCD == "ALT") %>% pull(ANRIND) %>% table()
> ```
> 
> this should be mainly low right?
> 
> ```
>   HIGH    LOW NORMAL 
>      0    394   2406 
> ```

There doesn't seem to be a distribution available to indicate how many should be in each level, just which levels should be used. Do you think there should be more/less `NORMAL`s for certain `PARAMCD`s?

**Comment by Melkiades** [comment]
> There doesn't seem to be a distribution available to indicate how many should be in each level, just which levels should be used. Do you think there should be more/less `NORMAL`s for certain `PARAMCD`s?

My intuition says yes, but maybe we should certify this. Btw if I complete the analysis:
```r
> a %>% filter(PARAMCD == "ALT") %>% select(ANRIND, BNRIND, ATOXGR, BTOXGR) %>% apply(2, table)
$ANRIND

   LOW NORMAL 
   394   2406 

$BNRIND

   LOW NORMAL 
   357   2443 

$ATOXGR

  -1   -2   -3   -4    0 
 121  116   93   64 2406 

$BTOXGR

  -1   -2   -3   -4    0 
 112  112   63   70 2443 
```

**Comment by Melkiades** [comment]
which makes sense because there are some LOW elements. doing the same with the old version of adlb and IGA:
```r
> a %>% filter(PARAMCD == "IGA") %>% select(ANRIND, BNRIND, ATOXGR, BTOXGR) %>% apply(2, table)
ANRIND BNRIND ATOXGR BTOXGR 
  2800   2800   2800   2800 
> a %>% filter(PARAMCD == "IGA") %>% select(ANRIND, BNRIND, ATOXGR, BTOXGR)
```

So I guess until some HIGH appears you did justice to the issue. Sorry for the roller coaster, unblocking this ;)

**Review by Melkiades — APPROVED** [review]

**Pull request merged**
